from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin

db = SQLAlchemy()

class User(UserMixin, db.Model):
    """User model"""

    __tablename__ = "cadusuarios"
    id = db.Column(db.Integer, primary_key=True)
    usuario = db.Column(db.String(25), unique=True, nullable=False)
    nome = db.Column(db.String(100), nullable=False)
    telefone = db.Column(db.String(15), nullable=False)
    emailcorp = db.Column(db.String(50), nullable=False)
    senha = db.Column(db.String(), nullable=False)

class Operations(db.Model):
    """Operation model"""

    __tablename__ = "cadoperacao"
    id = db.Column(db.Integer, primary_key=True)
    codcoligada = db.Column(db.Integer, unique=True, nullable=False)
    coligada = db.Column(db.String(50), unique=True, nullable=False)
    codfilial = db.Column(db.Integer, unique=True, nullable=False)
    filial = db.Column(db.String(50), unique=True, nullable=False)
    codoracle = db.Column(db.Integer, nullable=False)
    codlocation = db.Column(db.Integer,nullable=False)
    tagfpea = db.Column(db.String(50), nullable=False)
    codstatus = db.Column(db.Integer, nullable=False)
    status = db.Column(db.String(50), nullable=False)
    nomeprojeto = db.Column(db.String(50), nullable=False)
    dataquisicao = db.Column(db.DateTime(timezone=True), nullable=False)
    anoaquisicao = db.Column(db.Integer, nullable=False)
    mesaquisicao = db.Column(db.Integer, nullable=False)
    periodoaquisicao = db.Column(db.Integer, nullable=False)
    datahug = db.Column(db.DateTime(timezone=True), nullable=False)
    contaoperacao = db.Column(db.String(3), nullable=False)
    tipooperacao = db.Column(db.String(50), nullable=False)
    grupo = db.Column(db.String(50), nullable=False)
    macrodivisao = db.Column(db.String(50), nullable=False)
    maturacaooperacao = db.Column(db.String(50), nullable=False)
    grod = db.Column(db.String(50), nullable=False)
    rod = db.Column(db.String(50), nullable=False)
    rodcronico = db.Column(db.String(50), nullable=False)
    rodagudo = db.Column(db.String(50), nullable=False)
    rodoutras = db.Column(db.String(50), nullable=False)
    regiao = db.Column(db.String(50), nullable=False)
    regional = db.Column(db.String(50), nullable=False)
    uf = db.Column(db.String(2), nullable=False)
    municipio = db.Column(db.String(50), nullable=False)
    cnpj = db.Column(db.String(50), nullable=False)
    razaosocial = db.Column(db.String(50), nullable=False)
    cep = db.Column(db.String(50), nullable=False)
    logradouro = db.Column(db.String(50), nullable=False)
    numero = db.Column(db.String(50), nullable=False)
    complemento = db.Column(db.String(50), nullable=False)
    bairro = db.Column(db.String(50), nullable=False)
    endereco = db.Column(db.String(50), nullable=False)
    sindicato_preponderante = db.Column(db.String(50), nullable=False)
    mesbase_preponderante = db.Column(db.String(50), nullable=False)
    sindicato_enfermeiro = db.Column(db.String(50), nullable=False)
    mesbase_enfermeiro = db.Column(db.String(50), nullable=False)
    sindicatounificado = db.Column(db.String(50), nullable=False)
    cnpj_patronal_preponderante = db.Column(db.String(50), nullable=False)
    cnpj_classe_preponderante = db.Column(db.String(50), nullable=False)
    cnpj_patronal_enfermeiro = db.Column(db.String(50), nullable=False)
    cnpj_classe_enfermeiro = db.Column(db.String(50), nullable=False)
    encargo_parteempresa = db.Column(db.Float, nullable=False)
    encargo_terceiro = db.Column(db.Float, nullable=False)
    rat = db.Column(db.Float, nullable=False)
    fap = db.Column(db.Float, nullable=False)
    ratajustado = db.Column(db.Float, nullable=False)
    encargo_inss = db.Column(db.Float, nullable=False)
    encargo_fgts = db.Column(db.Float, nullable=False)
    encargo_total = db.Column(db.Float, nullable=False)
    provisao_ferias = db.Column(db.Float, nullable=False)
    provisao_tercoferias = db.Column(db.Float, nullable=False)
    provisao_decimoterceiro = db.Column(db.Float, nullable=False)
    encargo_provisao = db.Column(db.Float, nullable=False)
    encargo_totalprovisao = db.Column(db.Float, nullable=False)
    sistemacontabil = db.Column(db.String(50), nullable=False)

